### ISSUE TITLE
Core Use Case?

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-hackathon#11]
My vision for the core Use Case for DID:BTCR is at https://github.com/w3c/vc-use-cases/issues/31 — I encourage everyone to read it. I'd also love to continue to work with @jandrieu on moving the use case forward toward his full 15-step model that he did for Jorum during our hackathon if he is up for it. Maybe Natalie could help? @kimdhamilton?

**Comment by kimdhamilton** [comment]
tagging @nsmolenski

**Comment by nsmolenski** [comment]
Happy to help how I can! Just let me know.

**Comment by ChristopherA** [comment]
I've posted the basic #RebootingWebOfTrust user story to  this repository as [RWOT-User-Story.md](https://github.com/WebOfTrustInfo/btcr-hackathon/blob/master/RWOT-User-Story.md) — @jandrieu & @nsmolenski can hopefully take it from there to do a more formal use case [Joram](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2016/blob/master/final-documents/joram-engagement-model.pdf) style!

**Comment by kimdhamilton** [comment]
This issue was moved to WebOfTrustInfo/rebooting-the-web-of-trust-fall2017#13

**Comment by ChristopherA** [comment]
The local repository version of the [RWOT-User-Story.md](https://github.com/WebOfTrustInfo/btcr-hackathon/blob/master/RWOT-User-Story.md) has been updated with a more integrated version, and copied to the topics directory for next October's #RebootingWebOfTrust Design Workshop for developing further [topics-and-advance-readings/RWOT-User-Story.md](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2017/blob/master/topics-and-advance-readings/). cc: @jandrieu @nsmolenski
