### ISSUE TITLE
Simple non-PII skills claims?

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-hackathon#12]
As many of the core supporters of verified claims are desiring to do educational claims, I'm wondering if we can some support some very simple skill competency claims that are web-of-trust and don't have personally identifiable information, but are still useful.

For instance, I could make a claim that my DID I call by the local name/nym "BoB" claims that Bob's localname/nym of Alice has a high-proficiency in javascript.

**Comment by kimdhamilton** [comment]
I'm going to start with this in RWoT repo, and iterate from there:
https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2017/blob/master/topics-and-advance-readings/open-badges-as-verifiable-claims.md
