### ISSUE TITLE
Issues with Bitcoin Signed Playgrounds

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-hackathon#21]
There are some errors in the ecdsa-koblitz-pubkey as we are using it in our signature format and JSON-LD and Verifiable Claims playgrounds. Not sure where to put the issues for these, but may be depending on fixing them (or forking or replacing them) for the purposes of our hackathon.

The VC playground currently generates:
```
{
  "@context": [
    "https://schema.org/",
    "https://w3id.org/security/v1"
  ],
  "claim": {
    "id": "did:btc1:298347982739",
    "name": "Jane Doe",
    "jobTitle": "Professor",
    "telephone": "(425) 123-4567",
    "url": "http://www.janedoe.com"
  },
  "signature": {
    "type": "EcdsaKoblitzSignature2016",
    "created": "2017-07-07T23:46:14Z",
    "creator": "ecdsa-koblitz-pubkey:1LGpGhGK8whX23ZNdxrgtjKrek9rP4xWER",
    "signatureValue": "H1ngGC22jRP1P1XDNvanxzILATbbLo2SpqcseDHKyuY+KbBqYLk/KlKnP+SePVv3cPH+pIoXzPxuc32W8rZI7aY="
  }
}
```
However, in fact the value under creator, currently specified as 

    “creator": "ecdsa-koblitz-pubkey:1LGpGhGK8whX23ZNdxrgtjKrek9rP4xWER",

Is in fact not a public key, but base58-check hash of the public key.

The private key for our demo is also a base58check encoded value of the full private key: L4mEi7eEdTNNFQEWaa7JhUKAbtHdVvByGAqvpJKC53mfiqunjBjw

However, there is no standard base58-check for public keys (a prefix such that the value starts with 4 was proposed but never implemented), but there are tools you can see that the compressed public key (we don’t used uncompressed anymore) for that private in hex 020d79074ef137d4f338c2e6bef2a49c618109eccf1cd01ccc3286634789baef4b and the base58check is 1LGpGhGK8whX23ZNdxrgtjKrek9rP4xWER

Thus to correct, this means that the default example should look like:

    “creator": "ecdsa-koblitz-pubkey:020d79074ef137d4f338c2e6bef2a49c618109eccf1cd01ccc3286634789baef4b",

or possibly:

    “creator”: “ecdsa-koblitz-pubkey-hex:020d79074ef137d4f338c2e6bef2a49c618109eccf1cd01ccc3286634789baef4b”,

I’d actually prefer to use bech32 public key, which need some thinking about prefix but something like (not a correct value like the other ones as I don’t have a bech32 encoder working yet but just for reference):

    “creator”: “ecdsa-koblitz-pubkey-bech32:1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4”

The current way we are doing could be useful if a hash of the public key is useful for blinding purposes (I’m not sure if it actually is, as at best it should be memory hard like SCRYPT), but if it is supported, it would be something like:

     “creator”: “ecdsa-koblitz-pubkey-hash-base58check:1LGpGhGK8whX23ZNdxrgtjKrek9rP4xWER”,

There may be some way to specify encoding type in JSON-LD differently, but I’m not sure.

Another problem with the playground it is that it doesn’t have an issuer, and I’m confused on what the ID values should.

Here is a test with real bitcoin values that should validate with the current tools (if we had a working validator), and a real bitcoin key that I’m playing around with for my first real DID with a DDO (which will reside in my github at https://raw.githubusercontent.com/ChristopherA/self/master/ddo.jsonld )

```
{
  "@context": [
    "https://schema.org/",
    "https://w3id.org/security/v1"
  ],
  "id": "DID:BTCR:TBD#SOMEVALUE",
  "type": [
    "Credential",
    "WebOfTrustCredential"
  ],
  "issuer": "DID:BTCR:TBD#SOMEOTHERVALUE",
  "claim": {
    "id": "DID:BTCR:TBD#SOMETHIRDVALUE",
    "alternatename": "ChristopherA",
    "url": "https://raw.githubusercontent.com/christophera/self/master/ddo.jsonld",
    "publicKey": "02c490e19e936efab022bd9fc12833db082706473fd96cec14c4a8dac058a0dbee"
  },
  "signature": {
    "type": "EcdsaKoblitzSignature2016",
    "created": "2017-07-08T00:21:53Z",
    "creator": "ecdsa-koblitz-pubkey:1P8BWgokGDiqPYc3kgDDgn5Vm9XD1YUjEe",
    "signatureValue": "H/2e5KiopVH3glkoDf/yP/dwScEP0HPZioxNffvalkyUFYDX7OJ/4uKs6gPqjCISpR3DUe1PKTOVE6MSSTS8AeE="
  }
}
```

**Comment by kimdhamilton** [comment]
I am not sure we need a separate `issuer`, but there are several assumptions I'm making. (Below I will sidestep the other issue with `ecdsa-koblitz-pubkey:` encoding.)

Assumptions:

- `creator` is a key owned by the `issuer`. This seems like a common scenario, but (on my read) isn't necessarily obvious from the data model. OTOH, if not, the signature has no bearing on the issuer, so it's useless
- `creator` in the signature block could be an owner key listed in the DDO, as it uniquely identifies a key description (a fragment is needed if there is >1 owner key in the DDO)

Per the [Linked Data signature spec](https://w3c-dvcg.github.io/ld-signatures/)'s description of `creator`, I believe we can have a `creator` value like this:

```
"creator": "DID:BTCR:TBD_ISSUER#KEY_i"
```

That is, if the issuer's DID is `DID:BTCR:TBD_ISSUER`, the DDO has >1 owner key, and KEY_i is the DID+fragment uniquely identifying the signing key.

This is because the issuer DID is uniquely determined by the `creator` value. That is, if my many assumptions are right.

**Comment by ChristopherA** [comment]
New playground supporting testnet keys from @harlantwood https://peaceful-inlet-31266.herokuapp.com/playground/

**Comment by kimdhamilton** [comment]
Verify signing with testnet keys. Also verify pubkeys

**Comment by harlantwood** [comment]
The demo Christopher links to is from a PR here: https://github.com/json-ld/json-ld.org/pull/524/files

Although it should probably be in this repo instead: https://github.com/w3c-vc/playground/issues/3

**Comment by kimdhamilton** [comment]
verified @harlantwood's changes
