### ISSUE TITLE
"id=?" in verifiable claims

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-hackathon#23]
I tried to puzzle through a valid DDO as a verifiable claim at https://raw.githubusercontent.com/ChristopherA/self/master/ddo.jsonld a number of issues came up.

```json
{
  "@context": [
    "https://schema.org/",
    "https://w3id.org/security/v1"
  ],
  "id": "DID:BTCR:TBD#SOMEVALUE",
  "type": [
    "Credential",
    "WebOfTrustCredential"
  ],
  "issuer": "DID:BTCR:TBD#SOMEOTHERVALUE",
  "claim": {
    "id": "DID:BTCR:TBD#SOMETHIRDVALUE",
    "alternatename": "ChristopherA",
    "url": "https://raw.githubusercontent.com/christophera/self/master/ddo.jsonld",
    "publicKey": "02c490e19e936efab022bd9fc12833db082706473fd96cec14c4a8dac058a0dbee"
  },
  "signature": {
    "type": "EcdsaKoblitzSignature2016",
    "created": "2017-07-08T00:21:53Z",
    "creator": "ecdsa-koblitz-pubkey:1P8BWgokGDiqPYc3kgDDgn5Vm9XD1YUjEe",
    "signatureValue": "H/2e5KiopVH3glkoDf/yP/dwScEP0HPZioxNffvalkyUFYDX7OJ/4uKs6gPqjCISpR3DUe1PKTOVE6MSSTS8AeE="
  }
}
```

First as per #21 we don't have the right format for koblitz public keys (ecdsa-koblitz-pubkey isn't a public key, it is a hash). There are questions regarding issuer and owner. 

But there are a number of questions about the ID numbers.

First, walking through the scenario: We will have a master public key that is same as the one on the DID transaction. I presume this is what the DDO verifiable claim would be signed with.  I presume this key can be referred to as "DID:BTCR:TX1RK63UVXF9PQCSY" (btw, @jonasschnelli's actual DID).

It there is no DDO (which would be true for DID:BTCR:TX1RK63UVXF9PQCSY) that key is the only key — there are no others.

However, if the DDO exists it could, and probably should, have other public keys in it. As long as the key signing the DDO has not been revoked, they can be used to sign other verifiable claims (possibly with some future designe limitations). These keys could be non-koblitz keys (for instance, my PGP key or my 25519 miniLock key (BTW, which is 7rXYBKi1Xf9g9nupb9f8u6MHbobEJCMK3r3sChjN5RmGN )

How should we point to these other keys? I presume that is where the #SOMEVALUE is used. In the DID spec these are called DID Fragments:

    DID fragment. The portion of a DID reference that follows the first hash sign
    character ("#").

    A DID fragment MUST be used only as a method- independent pointer into the DDO
    to identify a unique key description or other DDO component. To resolve this pointer,
    the complete DID reference including the DID fragment MUST be used as the value of
    the id key for the target JSON object.

So in my example above, is the public key in my claim # 1? How do we mark them? For my prototype, I'd like be able to refer to 3 keys, a master koblitz, a second koblitz only valid for signing keys during the duration of this ddo, and my pgp key.

**Comment by kimdhamilton** [comment]
Again, I have more questions than answers.

If we had multiple owner keys in the DDO format, using an example from the [DID spec](https://opencreds.github.io/did-spec/#ddos-(did-descriptor-objects)), we'd have:
```
{
  "owner": [{
    "id": "did:example:21tDAKCERh95uGgKbJNHYp#key/1",
    "type": ["CryptographicKey", "EdDsaSAPublicKey"],
    "curve": "ed25519",
    "expires": "2017-02-08T16:02:20Z",
    "publicKey": "IOmA4R7TfhkY...Mq2/gi25s="
  }, {
    "id": "did:example:21tDAKCERh95uGgKbJNHYp#key/2",
    "type": ["CryptographicKey", "RsaPublicKey"],
    "expires": "2017-03-22T00:00:00Z",
    "publicKeyBase64": "MIIBOg...mgQaRyV"
  }]
}
```
I am under the impression that the fragments are simply unique identifiers within the owner array. (I'd like to be corrected if that's wrong). Using your example, in DDO format, I think we can have:

```
{
  "owner": [{
    "id": "DID:BTCR:TBD#YOUR_MASTER_KOBLITZ",
    ...
    "publicKey": "02c490e19e936efab022bd9fc12833db082706473fd96cec14c4a8dac058a0dbee"
  }, {
    "id": "DID:BTCR:TBD#YOUR_SECOND_KOBLITZ",
    ...
    "publicKey": "<encoding of your second koblitz public key is>"
  }, {
    "id": "DID:BTCR:TBD#YOUR_PGP",
    ...
    "publicKey": "<encoding of your PGP public key is>"
  }

]
}
```

And that these fragments can be any unique identifiers you choose, e.g. "YOUR_PGP" could be "key-3".


I am not sure yet how the DDO is translated into a Verifiable Claim. In your example above, are `claim`s meant to be owner keys? If so, could we translate my DDO into a VC by making an array of claims like this?

```
"claim": [{
    "id": "DID:BTCR:TBD#YOUR_MASTER_KOBLITZ",
    ...
    "publicKey": "02c490e19e936efab022bd9fc12833db082706473fd96cec14c4a8dac058a0dbee"
  },
{
    "id": "DID:BTCR:TBD#YOUR_SECOND_KOBLITZ",
    ...
},
{
    "id": "DID:BTCR:TBD#YOUR_PGP",
    ...
}
]

```

**Comment by kimdhamilton** [comment]
confirm with Manu and Dave that we're doing correctly

**Comment by kimdhamilton** [comment]
This issue was moved to w3c-ccg/did-spec#18
