### ISSUE TITLE
Given a DID, get the transaction (python implementation)

### ISSUE THREAD

**Issue by kimdhamilton** [WebOfTrustInfo/btcr-hackathon#31]
The input would be a bech32-encoded transaction, which is used by both BTCR and TX1.

From this, get the transaction (and DDO)

This issue tracks the python implementation.

**Comment by kimdhamilton** [comment]
Add repo when finished

**Comment by kimdhamilton** [comment]
Latest code and tests for js implementation are here: https://github.com/WebOfTrustInfo/txref-conversion-js

**Comment by joaosantos15** [comment]
Added to [repo](https://github.com/WebOfTrustInfo/txref-conversion-python). 
Created [issue](https://github.com/WebOfTrustInfo/txref-conversion-python/issues/1) to track the implementation updates to match @kimdhamilton [txref-conversion-js](https://github.com/WebOfTrustInfo/txref-conversion-js)
