### ISSUE TITLE
txid to bech encoding conversion playground

### ISSUE THREAD

**Issue by kimdhamilton** [WebOfTrustInfo/btcr-hackathon#36]
- [x] show block height/pos
- [x] call the field txref rather than did
- [ ] explanatory text
- [x] link to DDO
- [ ] owner key
- [ ] change of control proof in main section
- [ ] block hash
- [ ] merkle tree and date in signature block
- [ ] different apis

**Comment by ChristopherA** [comment]
See also #34 — does your tool agree with libbtc's answer?

**Comment by kimdhamilton** [comment]
available here: https://weboftrustinfo.github.io/btcr-tx-playground.github.io/

**Comment by kimdhamilton** [comment]
- show block height/pos
- different apis
- explanatory text

**Comment by kimdhamilton** [comment]
@ChristopherA I'm not sure from that issue what libbtc's answer is, but the items @shannona is posting (which I think are the latest outputs) are definitely different. The result length (non-prefix part) is 2 chars longer. I thought mine handled testnet, but perhaps the way testnet is handled changed.

So yeah, basically not sure anymore what our source of truth is...

**Comment by kimdhamilton** [comment]
prefix has changed to txtest1:

- https://github.com/jonasschnelli/bitcoin_txref_code.git
- https://github.com/jonasschnelli/bitcoin_txref_code/blob/master/ref/c/tests.c

**Comment by kimdhamilton** [comment]
from @ChristopherA: also use blockcypher data to extract essential data from transaction need for deterministic DDO...DDO pointer, owner key, change of control proof in main section, and block hash & merkle tree and date in signature block.

**Comment by kimdhamilton** [comment]
Code is updated to match Jonas's latest. Code moved to [https://github.com/WebOfTrustInfo/txref-conversion-js](https://github.com/WebOfTrustInfo/txref-conversion-js)

**Comment by kimdhamilton** [comment]
This issue was moved to WebOfTrustInfo/btcr-tx-playground.github.io#1
