### ISSUE TITLE
Need new class of keys because of overloaded Owner Keys

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-hackathon#38]
We have a problem in our DID specification where we are assuming that owner keys are what is also used for signing claims. This is causing us a number of problems in the BTCR method.

What we are discovering is that what the spec says owner key is used for is overloaded.

Instead, I suggest that the owner key(s) are ONLY used for signing DDO objects. 

What we need is another list, with a name TBD but is basically the "claim issuer keys", which are in a DDO, signed by the owner keys, which are keys allowed to be used to sign names. This list may, or may not, include the owner key, but if the list doesn't exist, then the owner key is presumed to be one of them.

cc: @talltree @msporny @dlongley

**Comment by kimdhamilton** [comment]
Ryan and @ChristopherA working on MVP DID Spec. Goal: lessons from hackathon, focus on what is in DDR spec is minimum required for BTCR, make suggestions on what in current DID spec maybe should be moved to method specs.

**Comment by msporny** [comment]
Agreed that this is an issue, we hit it this past weekend talking through the spec w/ @talltree in Washington DC.

We need to start considering moving to a capabilities based security model for keys and avoiding the ambient authority security issues that we seem to be marching into.

That is, we should have key attributes in the DDO that are very specific when it comes to what the keys listed can do. Something like:

``` javascript
"pocAuthorization": { // proof of control authorization field
  // key details go here... capability is 'proof of control' ... object is the DDO
}
```

**Comment by msporny** [comment]
@kimdhamilton wrote:
> Ryan and @ChristopherA working on MVP DID Spec. 

"DID Spec"? Or "BTC DID Method Spec"?

The DID Spec is this: https://opencreds.github.io/did-spec/

**Comment by ChristopherA** [comment]
Sounds like we are in general agreement here. I would very narrowly define each capability — I'd rather have the same proof be presented with multiple capabilities rather than overloading a capability.

Another insight from BTCR — whenever you see the word "key", consider not using it. Instead, it is a signature proof, where there may be many other forms of proof in the future. i.e.

```
"pocAuthorization": { 
  // proof details go here
```

**Comment by ChristopherA** [comment]
In my opinion after the hackathon, which I believe we all concure on is that the current DID draft at https://opencreds.github.io/did-spec/ has many features in it that are a) not required or are not possible in BTCR, and b) many features in it that probably shouldn't be in that spec at all, but another layer.

In particular, guardian is totally broken. A particular proof may be able to be presented by a guardian for different capabilities, and maybe that role is tagged as part of that proof, but it is not a first-order capability.

**Comment by kimdhamilton** [comment]
This issue was moved to opencreds/did-spec#13
