### ISSUE TITLE
Insight for DID spec: proofs, not keys

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-hackathon#39]
An insight from the work this week is we should not be talking about owner key, or control key, etc.

Instead, we should be talking about proofs.

For instance, this fragment from a DDO

  {
          "control": 
          [{
              "control-bond": 1.25
              "rotate-proof": [{
                  "proof-type": "pubkeyhash",
                  "bond-value": 1.25
                  "hash-base58check": "mvZ3MyLgsvYr87GGSbsPBWEDduLRptfzEU"
                  }]
            },{
            "revocation-proof": [{
                "bond-value": 1.25
                "proof-type": "pubkeyhash",
                "hash-base58check": "mvZ3MyLgsvYr87GGSbsPBWEDduLRptfzEU"
          }]
        }

It basically says that for control (which permits rotating the owner key and the DDO address) that there are two subtypes, a rotate proof and a revocation proof. In another ddo system the proof-type could be "signature", or even "revocation list".

Similar with owner (which permits updating of the keys allowed to issue claims, and the other content of the DDO, but not the control key or the DDO address), it can be proofs as well which may not just be signatures.

cc: @talltree @msporny @dlongley

**Comment by kimdhamilton** [comment]
TODO: insights and links from BTCR hackathon

**Comment by ChristopherA** [comment]
I started this at https://github.com/opencreds/did-spec/issues/4#issuecomment-315449659

I'd like to see a paragraph or so from each of us of top lessons learned, and important links to code, text, or issues contributed to.

**Comment by msporny** [comment]
I suggest we start moving a lot of these issues to the DID spec issue repository. @talltree, @dlongley, and I met in DC this past week to go through a revision of the DID spec that Digital Bazaar needs so it can align it w/ our implementation and thinking. I expect this will be an area of focus at the next RWoT.

Specifically, a capabilities based security model for DDOs and what you can do w/ keys associated w/ DIDs.

**Comment by ChristopherA** [comment]
Moving these issues is in progress — many of the issues from this hackathon have already been moved there. @kimdhamilton found a useful tool that moves them intact.

**Comment by talltree** [comment]
Christopher and Kim,

I'm glad to see these issues move to the DID spec issue repository. Are you
planning for these to start being discussed on the weekly calls, or should
we start planning a dedicated weekly or bi-weekly called on the DID spec.
There is a lot of work to do here and implementations are already underway,
which creates pressure to do it quickly.

Thanks,

=Drummond

On Sun, Jul 16, 2017 at 9:21 PM, Christopher Allen <notifications@github.com

**Comment by kimdhamilton** [comment]
I'm open to both. Btw, tomorrow we have about 15 minutes that you (and/or Manu) can spend on DID topics as you see fit. Given the priority of this spec, I imagine we could carve out a large amount of time for the weekly meeting on an ongoing basis. As the year proceeds, we could juggle the weekly meeting focus. 

It's possible that even this won't be enough, so we could have either dedicated recurring or off-by-one meetings as well.

@ChristopherA what do you think?

**Comment by talltree** [comment]
Kim, thanks. Evernym has a company summit this week so my time on the call
tomorrow will be limited. I'll try to get on the chat and watch for it on
the agenda so I can be sure to join for that segment at least.

=Drummond

**Comment by kimdhamilton** [comment]
This issue was moved to w3c/vc-data-model#62
