### ISSUE TITLE
Close every issue by resolving it, moving it, or documenting it, with two-way links

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-hackathon#44]
All that we've learned here should be shared. All the issues should be resolved (if it is a simple bug or something not worth sharing), moving the issue to the appropriate repository (for instance the DID spec repo https://github.com/opencreds/did-spec/issues/ or in this Fall's #RebootingWebOfTrust repo https://github.com/weboftrustinfo/rebooting-the-web-of-trust-fall2017/issues), writing up report or topic (for publication in W3C Credentials CG or for this Fall's #RebootingWebOfTrust topics).

All such links should point both ways, back to this repo and this repo should document where they were moved to.

This should be the penultimate (second to last) issue closed here.

**Comment by kimdhamilton** [comment]
https://github-issue-mover.appspot.com/
