### ISSUE TITLE
Holds and Timelocks

### ISSUE THREAD

**Issue by ChristopherA** [WebOfTrustInfo/btcr-hackathon#6]
Related to issue #5 it may be useful to have a "DID hold" op_return with a date, such that the DID is not considered revoked, but that it isn't valid yet. This way you can pre-publish a DID.

There also may be some useful tricks by adding to the P2PKH transaction a timelock.

**Comment by kimdhamilton** [comment]
This issue was moved to WebOfTrustInfo/rebooting-the-web-of-trust-fall2017#19

**Comment by kimdhamilton** [comment]
This issue was moved to WebOfTrustInfo/rebooting-the-web-of-trust-fall2017#35
